Repository JCSDA/spack, pull requests merged in 2024-08, with the labels that each got.

#459 Add ecmwf-atlas versions 0.38.0, 0.38.1
  var/spack/repos/builtin/packages/ecmwf-atlas/package.py
Labels: INFRA

#458 Add esmf@8.7.0bs11
  var/spack/repos/builtin/packages/esmf/package.py
Labels: NAVY

#460 Replace previous solution to suppress Intel's deprecation warnings with spack-blesssed version
  lib/spack/env/cc
  lib/spack/spack/compilers/intel.py
  lib/spack/spack/compilers/oneapi.py
  lib/spack/spack/test/build_environment.py
  lib/spack/spack/test/cc.py
Labels: enhancement

#461 Introduce the bufr_query library from NOAA-EMC
  var/spack/repos/builtin/packages/bufr-query/package.py
  var/spack/repos/builtin/packages/bufr-query/site-packages.patch
Labels: INFRA
