Repository JCSDA/spack, pull requests merged in 2024-07, with the labels that each got.

#448 mepo: new package (spack#44879)
  var/spack/repos/builtin/packages/mepo/package.py
  var/spack/repos/builtin/packages/py-pyyaml/package.py
Labels: NASA

#450 Updates towards compiling full unified environment with Intel oneAPI compilers (icx, icpx, ifort)
  lib/spack/env/cc
  var/spack/repos/builtin/packages/fckit/package.py
  var/spack/repos/builtin/packages/qt/package.py
  var/spack/repos/builtin/packages/qt/qt51514-oneapi.patch
Labels: enhancement

#451 Remove release-jcsda version related code in fms package.py script
  var/spack/repos/builtin/packages/fms/package.py
Labels: INFRA
