Repository JCSDA/spack, pull requests merged in 2024-12, with the labels that each got.

#488 Updated version specs for bufr-query package. (#47752)
  var/spack/repos/builtin/packages/bufr-query/package.py
Labels: INFRA

#489 Cherry-pick from spack develop: py-uxarray with dependencies, update of ECMWF packages
  var/spack/repos/builtin/packages/eckit/package.py
  var/spack/repos/builtin/packages/ecmwf-atlas/package.py
  var/spack/repos/builtin/packages/ectrans/package.py
  var/spack/repos/builtin/packages/fckit/package.py
  var/spack/repos/builtin/packages/fiat/package.py
  var/spack/repos/builtin/packages/py-antimeridian/package.py
  var/spack/repos/builtin/packages/py-bokeh/package.py
  var/spack/repos/builtin/packages/py-dask-expr/package.py
  var/spack/repos/builtin/packages/py-dask/package.py
  var/spack/repos/builtin/packages/py-datashader/package.py
  var/spack/repos/builtin/packages/py-geoviews/package.py
  var/spack/repos/builtin/packages/py-holoviews/package.py
  var/spack/repos/builtin/packages/py-hvplot/package.py
  var/spack/repos/builtin/packages/py-panel/package.py
  var/spack/repos/builtin/packages/py-param/package.py
  var/spack/repos/builtin/packages/py-spatialpandas/package.py
  var/spack/repos/builtin/packages/py-uxarray/package.py
Labels: INFRA, NAVY

#492 Configure 'spack external find grep'
  var/spack/repos/builtin/packages/grep/package.py
Labels: enhancement
